main:
  - name: Posts
    pageRef: /posts
    weight: 10

  - name: Archives
    pageRef: /archives
    weight: 20

  - name: Projects
    pageRef: /projects
    weight: 25

  - name: Categories
    pageRef: /categories
    weight: 30

  - name: Tags
    pageRef: /tags
    weight: 40

footer:
  - name: Projects
    pageRef: /projects
    weight: 5

  - name: About
    pageRef: /about
    weight: 10

  - name: RSS Feed
    url: /index.xml
    weight: 20

social:
  - name: GitHub
    url: https://github.com/jiangbyte
    weight: 10
