main:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: Archives
    pageRef: /archives
    weight: 20
    params:
      icon: archive

  - name: Projects
    pageRef: /projects
    weight: 25
    params:
      icon: projects

  - name: Categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories

  - name: Tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags

# footer menu
footer:
  - name: Projects
    pageRef: /projects
    weight: 5
    params:
      icon: projects

  - name: About
    pageRef: /about
    weight: 10
    params:
      icon: about

  - name: RSS Feed
    url: /index.xml
    weight: 20
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/jiangbyte
    weight: 10
    params:
      icon: github

  - name: Email
    url: mailto:jiangbyte@example.com
    weight: 20
    params:
      icon: email
