# Blowfish theme parameters
colorScheme: "blowfish"
defaultAppearance: "light"
autoSwitchAppearance: true

enableSearch: true
enableCodeCopy: true

mainSections: ["posts"]

disableImageOptimization: false
hotlinkFeatureImage: true

header:
  layout: "fixed"

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

homepage:
  layout: "page"
  showRecent: true
  showRecentItems: 6
  showMoreLink: true
  showMoreLinkDest: "posts"
  cardView: true
  cardViewScreenWidth: false

article:
  showDate: true
  showDateUpdated: false
  showAuthor: true
  showHero: true
  heroStyle: "big"
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false

list:
  showSummary: true
  showViews: false
  showLikes: false
  groupByYear: false
  cardView: true

sitemap:
  showAuthor: true
  showSummary: true

enableA11y: false

# Default image fallback
defaultBackgroundImage: "https://api.yppp.net/pc.php"
defaultFeaturedImage: "https://api.yppp.net/pc.php"
